-- MySQL Script generated by MySQL Workbench
-- Wed Jul 13 22:19:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema leiteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leiteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leiteria` DEFAULT CHARACTER SET utf8 ;
USE `leiteria` ;

-- -----------------------------------------------------
-- Table `leiteria`.`racas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`racas` (
  `id_raca` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_raca`));


-- -----------------------------------------------------
-- Table `leiteria`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`usuarios` (
  `id_usuario` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `chefe` BIGINT NULL DEFAULT NULL,
  UNIQUE INDEX (`email` ASC),
  PRIMARY KEY (`id_usuario`),
  INDEX `usuarios_fk0` (`chefe` ASC),
  CONSTRAINT `usuarios_fk0`
    FOREIGN KEY (`chefe`)
    REFERENCES `leiteria`.`usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `leiteria`.`propriedades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`propriedades` (
  `id_propriedade` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL DEFAULT NULL,
  `localidade` VARCHAR(60) NULL DEFAULT NULL,
  `municipio` VARCHAR(60) NULL DEFAULT NULL,
  `id_proprietario` BIGINT NOT NULL,
  PRIMARY KEY (`id_propriedade`),
  INDEX `propriedades_fk0` (`id_proprietario` ASC),
  CONSTRAINT `propriedades_fk0`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `leiteria`.`usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `leiteria`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`animais` (
  `id_animal` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `brinco` INT NOT NULL,
  `data_nasc` DATE NOT NULL,
  `registro` BIGINT NOT NULL,
  `sexo` CHAR NOT NULL,
  `pai` VARCHAR(60) NULL DEFAULT NULL,
  `mae` VARCHAR(60) NULL DEFAULT NULL,
  `id_raca` INT NOT NULL,
  `id_propriedade` BIGINT NOT NULL,
  `id_pai` BIGINT NULL DEFAULT NULL,
  `id_mae` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_animal`),
  INDEX `animais_fk0` (`id_raca` ASC),
  INDEX `animais_fk1` (`id_propriedade` ASC),
  INDEX `animais_fk2` (`id_pai` ASC),
  INDEX `animais_fk3` (`id_mae` ASC),
  CONSTRAINT `animais_fk0`
    FOREIGN KEY (`id_raca`)
    REFERENCES `leiteria`.`racas` (`id_raca`),
  CONSTRAINT `animais_fk1`
    FOREIGN KEY (`id_propriedade`)
    REFERENCES `leiteria`.`propriedades` (`id_propriedade`),
  CONSTRAINT `animais_fk2`
    FOREIGN KEY (`id_pai`)
    REFERENCES `leiteria`.`animais` (`id_animal`),
  CONSTRAINT `animais_fk3`
    FOREIGN KEY (`id_mae`)
    REFERENCES `leiteria`.`animais` (`id_animal`));


-- -----------------------------------------------------
-- Table `leiteria`.`regras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`regras` (
  `nome_regra` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`nome_regra`));


-- -----------------------------------------------------
-- Table `leiteria`.`usuario_regras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`usuario_regras` (
  `id_usuario` BIGINT NOT NULL,
  `id_regra` VARCHAR(60) NOT NULL,
  CONSTRAINT `usuario_regras_fk0`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `leiteria`.`usuarios` (`id_usuario`),
  CONSTRAINT `usuario_regras_fk1`
    FOREIGN KEY (`id_regra`)
    REFERENCES `leiteria`.`regras` (`nome_regra`));


-- -----------------------------------------------------
-- Table `leiteria`.`animais_doadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`animais_doadores` (
  `id_doador` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `brinco` INT NULL DEFAULT NULL,
  `data_nasc` DATE NOT NULL,
  `registro` BIGINT NOT NULL,
  `pai` VARCHAR(60) NULL DEFAULT NULL,
  `mae` VARCHAR(60) NULL DEFAULT NULL,
  `id_proprietario` BIGINT NOT NULL,
  `teste_progenie` TINYINT NULL DEFAULT NULL,
  `nucleo_moet` TINYINT NULL DEFAULT NULL,
  `dono` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_doador`),
  INDEX `animais_doadores_fk0` (`id_proprietario` ASC),
  CONSTRAINT `animais_doadores_fk0`
    FOREIGN KEY (`id_proprietario`)
    REFERENCES `leiteria`.`usuarios` (`id_usuario`));


-- -----------------------------------------------------
-- Table `leiteria`.`semens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`semens` (
  `id_semen` BIGINT NOT NULL AUTO_INCREMENT,
  `touro_doador` BIGINT NOT NULL,
  `data_entrada` DATE NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_unitario` DOUBLE NULL DEFAULT NULL,
  `cod_palheta` INT NOT NULL,
  PRIMARY KEY (`id_semen`),
  INDEX `semens_fk0` (`touro_doador` ASC),
  CONSTRAINT `semens_fk0`
    FOREIGN KEY (`touro_doador`)
    REFERENCES `leiteria`.`animais_doadores` (`id_doador`));


-- -----------------------------------------------------
-- Table `leiteria`.`tipos_cobertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`tipos_cobertura` (
  `id_tipos_cobertura` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipos_cobertura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leiteria`.`coberturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`coberturas` (
  `id_cobertura` BIGINT NOT NULL AUTO_INCREMENT,
  `vaca` BIGINT NOT NULL,
  `tipo_cobertura` INT NOT NULL,
  `touro_monta` BIGINT NULL DEFAULT NULL,
  `inseminador` BIGINT NULL DEFAULT NULL,
  `semen` BIGINT(10) NULL DEFAULT NULL,
  `qtde_dose_semen` INT(255) NULL DEFAULT NULL,
  `data` DATE NOT NULL,
  `monta_controlada` TINYINT NULL DEFAULT NULL,
  `escore_corporal` DECIMAL(2,2) NULL DEFAULT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cobertura`),
  INDEX `coberturas_fk1` (`vaca` ASC),
  INDEX `coberturas_fk2` (`touro_monta` ASC),
  INDEX `coberturas_fk3` (`inseminador` ASC),
  INDEX `coberturas_fk4` (`semen` ASC),
  INDEX `fk_coberturas_tipos_cobertura1_idx` (`tipo_cobertura` ASC),
  CONSTRAINT `coberturas_fk1`
    FOREIGN KEY (`vaca`)
    REFERENCES `leiteria`.`animais` (`id_animal`),
  CONSTRAINT `coberturas_fk2`
    FOREIGN KEY (`touro_monta`)
    REFERENCES `leiteria`.`animais` (`id_animal`),
  CONSTRAINT `coberturas_fk3`
    FOREIGN KEY (`inseminador`)
    REFERENCES `leiteria`.`usuarios` (`id_usuario`),
  CONSTRAINT `coberturas_fk4`
    FOREIGN KEY (`semen`)
    REFERENCES `leiteria`.`semens` (`id_semen`),
  CONSTRAINT `fk_coberturas_tipos_cobertura1`
    FOREIGN KEY (`tipo_cobertura`)
    REFERENCES `leiteria`.`tipos_cobertura` (`id_tipos_cobertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `leiteria`.`metodos_prenhez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`metodos_prenhez` (
  `id_metodos_prenhez` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metodos_prenhez`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leiteria`.`diagnosticos_prenhez`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`diagnosticos_prenhez` (
  `id_diagnostico` BIGINT NOT NULL AUTO_INCREMENT,
  `vaca` BIGINT NOT NULL,
  `metodo_prenhez` INT NOT NULL,
  `cobertura` BIGINT NULL DEFAULT NULL,
  `data` DATE NOT NULL,
  `diagnostico` TINYINT NOT NULL,
  `observacao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_diagnostico`),
  INDEX `diagnosticos_prenhez_fk0` (`vaca` ASC),
  INDEX `diagnosticos_prenhez_fk1` (`cobertura` ASC),
  INDEX `fk_diagnosticos_prenhez_metodos_prenhez1_idx` (`metodo_prenhez` ASC),
  CONSTRAINT `diagnosticos_prenhez_fk0`
    FOREIGN KEY (`vaca`)
    REFERENCES `leiteria`.`animais` (`id_animal`),
  CONSTRAINT `diagnosticos_prenhez_fk1`
    FOREIGN KEY (`cobertura`)
    REFERENCES `leiteria`.`coberturas` (`id_cobertura`),
  CONSTRAINT `fk_diagnosticos_prenhez_metodos_prenhez1`
    FOREIGN KEY (`metodo_prenhez`)
    REFERENCES `leiteria`.`metodos_prenhez` (`id_metodos_prenhez`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `leiteria`.`tipos_parto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`tipos_parto` (
  `id_tipos_parto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipos_parto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leiteria`.`partos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leiteria`.`partos` (
  `id_parto` BIGINT NOT NULL AUTO_INCREMENT,
  `vaca` BIGINT NOT NULL,
  `cobertura` BIGINT NULL DEFAULT NULL,
  `prenhez` BIGINT NULL DEFAULT NULL,
  `tipo_parto` INT NOT NULL,
  `data` DATE NOT NULL,
  `escore_corporal` DECIMAL(2,2) NULL DEFAULT NULL,
  `qtde_crias` INT NOT NULL,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_parto`),
  INDEX `partos_fk0` (`vaca` ASC),
  INDEX `partos_fk1` (`cobertura` ASC),
  INDEX `partos_fk2` (`prenhez` ASC),
  INDEX `fk_partos_tipos_parto1_idx` (`tipo_parto` ASC),
  CONSTRAINT `partos_fk0`
    FOREIGN KEY (`vaca`)
    REFERENCES `leiteria`.`animais` (`id_animal`),
  CONSTRAINT `partos_fk1`
    FOREIGN KEY (`cobertura`)
    REFERENCES `leiteria`.`coberturas` (`id_cobertura`),
  CONSTRAINT `partos_fk2`
    FOREIGN KEY (`prenhez`)
    REFERENCES `leiteria`.`diagnosticos_prenhez` (`id_diagnostico`),
  CONSTRAINT `fk_partos_tipos_parto1`
    FOREIGN KEY (`tipo_parto`)
    REFERENCES `leiteria`.`tipos_parto` (`id_tipos_parto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
